name: CI CD Github Action Practice
on: 
  workflow_dispatch:
jobs:
  Abhay-job-1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checckout step
        uses: actions/checkout@v7.0.0
      
      - name: Good Morning Greetings
        run: echo Hello Honey, Good Morning ..!
      


  
  # job2:
  # job3:
  
